### ISSUE TITLE
Documentation/implementation for setting up configuration data

### ISSUE THREAD

**Issue by DonThompson** [dlmelendez/identityserver4-azurestorage#12]
Hi David,

This is a neat idea for storage and I'm taking a look at it for a little hobby project I have coming up, thanks so much!

I notice your readme says "Use the unit tests as a guide to seeding operational and configuration data.".  I've written a little class that just takes the data from Identity Server's Config class (most folks implementing IS4 are probably familiar with this already) and inserts it into the table storage.  It's not much, but it might make things a little easier for the next implementer.

Would you be interested in reviewing/including this if I make a PR?

**Comment by dlmelendez** [comment]
Yes. Are you thinking a simple command line project for this?

**Comment by DonThompson** [comment]
So far it's just a simple class that you could throw in ConfigureServices() after setting up your storage configuration (similar to the one time code you've got in your documentation).  I'll take a look and see if I can quickly convert it to a command line app.  Other option would just be to include the class in your documentation and anyone can pull it down/copy it to do a one time initialization.

**Comment by DonThompson** [comment]
The console app didn't quite feel right yet - this is really more "Here's a quick primer on how to create new api/identity/client resources."  I figure it's better as documentation at this point, might be enhanced later.  I think a user would assume a console app could actually allow them to manage the data.
Let me know what you think and I can adjust as needed.

**Comment by dlmelendez** [comment]
Closed for inactivity.
