### ISSUE TITLE
Latest IdentityServer4 version 4 support

### ISSUE THREAD

**Issue by hokusp** [dlmelendez/identityserver4-azurestorage#14]
Hi,

First of all thank you very much for that project!
Unfortunately it seems that it is not compatible with the newest version of IdentityServer. It looks like `IPersistedGrantStore` did change.
Do you plan to update the project?

Thanks and best regards

**Comment by dlmelendez** [comment]
Yes. Support for IdentityServer4 v4 is on the way. I was planned update after .NET 5 releases in November, approx December timeframe. I will get the milestone setup. Thanks for the interest.

**Comment by hokusp** [comment]
very good news!

**Comment by dlmelendez** [comment]
v2.0 is complete with support for IdentityServer4 v4.
