### ISSUE TITLE
The type initializer for 'ElCamino.IdentityServer4.AzureStorage.Mappers.PersistedGrantMappers' threw an exception.

### ISSUE THREAD

**Issue by pollumi** [dlmelendez/identityserver4-azurestorage#21]
Hi,

I'm getting the following exception:

> [20:04:45 FTL] Unhandled exception: The type initializer for 'ElCamino.IdentityServer4.AzureStorage.Mappers.PersistedGrantMappers' threw an exception.
> System.TypeInitializationException: The type initializer for 'ElCamino.IdentityServer4.AzureStorage.Mappers.PersistedGrantMappers' threw an exception.
>  ---> System.MissingMethodException: Method not found: 'AutoMapper.IMappingExpression`2<!0,!1> AutoMapper.IMappingExpression`2.ConstructUsing(System.Linq.Expressions.Expression`1<System.Func`2<!0,!1>>)'.
>    at ElCamino.IdentityServer4.AzureStorage.Mappers.PersistedGrantMappers.<>c.<.cctor>b__10_0(IMapperConfigurationExpression cfg)
>    at AutoMapper.MapperConfiguration.Build(Action`1 configure)
>    at AutoMapper.MapperConfiguration..ctor(Action`1 configure)
>    at ElCamino.IdentityServer4.AzureStorage.Mappers.PersistedGrantMappers..cctor()
>    --- End of inner exception stack trace ---
>    at ElCamino.IdentityServer4.AzureStorage.Mappers.PersistedGrantMappers.ToEntities(PersistedGrant persistedGrant)
>    at ElCamino.IdentityServer4.AzureStorage.Stores.PersistedGrantStore.StoreAsync(PersistedGrant grant)
>    at IdentityServer4.Stores.DefaultGrantStore`1.StoreItemAsync(String key, T item, String clientId, String subjectId, String sessionId, String description, DateTime created, Nullable`1 expiration, Nullable`1 consumedTime)
>    at IdentityServer4.Stores.DefaultGrantStore`1.CreateItemAsync(T item, String clientId, String subjectId, String sessionId, String description, DateTime created, Int32 lifetime)
>    at IdentityServer4.Stores.DefaultRefreshTokenStore.StoreRefreshTokenAsync(RefreshToken refreshToken)
>    at IdentityServer4.Services.DefaultRefreshTokenService.CreateRefreshTokenAsync(ClaimsPrincipal subject, Token accessToken, Client client)
>    at IdentityServer4.ResponseHandling.TokenResponseGenerator.CreateAccessTokenAsync(ValidatedTokenRequest request)
>    at IdentityServer4.ResponseHandling.TokenResponseGenerator.ProcessTokenRequestAsync(TokenRequestValidationResult validationResult)
>    at IdentityServer4.ResponseHandling.TokenResponseGenerator.ProcessAsync(TokenRequestValidationResult request)
>    at IdentityServer4.Endpoints.TokenEndpoint.ProcessTokenRequestAsync(HttpContext context)
>    at IdentityServer4.Endpoints.TokenEndpoint.ProcessAsync(HttpContext context)
>    at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events, IBackChannelLogoutService backChannelLogoutService)

Do you have any hints what I may be missing?

Using `ElCamino.IdentityServer4.AzureStorage` 2.0.1
and `IdentityServer4` 4.1.1

Thanks!

**Comment by pollumi** [comment]
I used `ElCamino.IdentityServer4.AzureStorage` with sources and updated `AutoMapper` to 10.1.1 and now everything works.

**Comment by dlmelendez** [comment]
Unable to repo.
